[project]
name = "ment-torch"
version = "0.0.1"
dependencies = []

[build-system]
requires = [
    "setuptools>=62",
    "setuptools_scm>=6.2",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["ment_torch"]
